server:
  port: 7000
spring:
  application:
    name: atguigu-crowd-pay
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.42.131
  session:
    store-type: redis
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqDrlROz9jKV+jQeBYN4+dK9i0TXVlb+ScxGgdyEyH4vNNO9f4vJk6hvkui/FUxJvneMxOiWQVDSybepp3N59y2lwumEfKiy0M3vJWY4Ww/T4SN9XEl9hQXSMgmNmyws6erPNBvVtfF2spEteKLQpirdP+72T0/7lGTrr1P3JJcrq7d1gNgmh+x2QUK99G+H/kGmntneArexad1pcDNtIy62aIfbGVLdldn4UXeKuLEgj1w9d+Kf6O4VS6Ai+GCdP2oa5oMq7aj/2EfPO1azr8t/z6eGZFvjYfwYfxkJUbTpMV8CE022rY9oN/C6n1um0yZygm9MjHzM3KQJgfOicMQIDAQAB
    app-id: 2021000118634709
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCCKkdZn4u1C/BrHYnCi7o7CdSIwUM1OpcdqxEfr+PGxa5fSNMecFOKXUbE2xFUC8MWKA1CwkHg3qcUEbBPrOIq6hsidJIh8EDX8/KgWyG7+l3cWg/jy3a+5XYw+pGlgoI43DLNR/m5DebXbh9+8dmgK74gdptME0wlx/geODtFw69MLE5z4SVHDMoPlj3/t3Ft1xKWze/Jm5/J0Hy6Izim25X+rvKBxeNLKF92Ya+xICg3SE/qklxahB4YvR+YDQcFwO6+/tacd8MdNJ8x5FZldxE7R2VX3tmlnzcInfeo79RWlgY5Eh5pKzu21jnOQDk0+1Ebax/DDWlN2gJKlBdNAgMBAAECggEAETOvLDv2hZ2nTzCfJRO8L9MzwELyM9WjZOtXnv1qt7kmOzdvlyU3FSEQmjFtT9MiHAp8/iaX+DTUlcVkrJLnbM51eY84RL3wg9mcZe7FPYdv4hAQ64TXE5FVllF28A2YUhVfrVtmuDsLF8tY5DjoDs/ZF4c1LM+cD54mvy+lPanXTxPUsuay3UbmPzyXSsh6zfoKF0M6Act3b0j7nYyCFuBCrtgWd9NJ5F82hQdSzY2Aa0yRJTI3F2RdWNCIGyRCp9A4i+fjLCAzul5XHEah8I3cNHSlQiOxAuhhIzdjYSdpyBg+TkMbxgD3U0ghkacXdnkNVRn94O43JCp7PcajQQKBgQDHj4Qznd8b/wJViO7ydpJl42ZeVMoyBucCLf8lyb5fVz5Jy83AFFxCBFgI26fj5GcWxAcxdAkImLZ7BvDIO5hqJ/nlaORYz6naGLNZhmudU6L0FVTy6wzQeBfZI+GrhhIQYiXehuWxd7f+PzuS6wGjn836l8XJOcI46gHVoCHl8QKBgQCm+m2laSoYD587zPJbMLbsyYVsEZ5/c74gYTE6XtkFjDKT1/8KhuYMDKQX70uUgDBVrOwJ3kYLjxkiork/0DFngyguqgFV3fdiVeAjdAdcyOLIGeRTqWpXuYhPsCqPVacV37811teurSZZvyZn0Ves6qwtGWfUMFJttg5IYia7HQKBgG2kPUc6usUf84FZLadLXB3ctXaocTrRLgS1jtSNJiotvcw/zDh3N0USK+gZ/wEnkTgh1a3nCbuOY9vuMUZh79iLRDI10he1aKWqIofSYbfbptEiEz0vxSeYg8nKfAeILs6PjizXwsUheJaY2TtcINdsSngfAQ0QzdQFRaLASz+RAoGAfKqIZnEH7oLrXdh8Mb1DNbKXnMHi1kFx9/bYrD3YRh4QPPWNAy0IYIKnmP8eLLcwXycF67A6F7M1Dvjy2kP0PtZbj8t5x8Q7SP3YpF+ih5GsT72VDSl1rh1lOinK/Mz0PI6a0fWffljkQylF4UkY7o8fEWTgcjnJsQO10jEFvbkCgYACyFUAK8eR0vggha7O2M8b7zFoPEJUoFWsf+VzlmRTSjdNgMNg+M1AcgNCGkuk9w+yA8i/gYlureclBMB+qucPLS1U45JU1GYt2by0hDBrllchSuShEM3gMgWpqxXb9PDS1Esi5aEa+ihzRcc7c9azZ7qQ7yOgymQWwkCmslpg9Q==
    notify-url: http://4ava2u.natappfree.cc/pay/notify
    return-url: http://localhost/pay/return
    sign-type: RSA2
